# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Bayesian p-value
#'
#' @description
#' Calculates Bayesian equivalent of frequentist p-value
#' from vector of posterior samples.
#'
#' @param x numeric vector of posterior samples
#' @return Bayesian equivalent of p-value.
#' @useDynLib jaggernaut
bayesian_p_value <- function(x) {
    .Call('jaggernaut_bayesian_p_value', PACKAGE = 'jaggernaut', x)
}

