# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Hello world
#'
#' @description
#' You know what this does - its foobar
#'
#' @useDynLib jaggernaut
#' @export
hello_world <- function() {
    .Call('jaggernaut_hello_world', PACKAGE = 'jaggernaut')
}

